server:
  port: 8081

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.exchange
      routing-key:
        producer: rk.producer
      deadletter:
        producer: dl.producer
      parking-lot:
        producer: pl.producer